# Generated by Django 5.1.2 on 2024-10-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
