# Generated by Django 5.1.2 on 2024-10-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_recycle_alter_users_email_alter_users_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
        migrations.RenameModel(
            old_name='orderproducts',
            new_name='orderproduct',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
