# Generated by Django 5.1.2 on 2024-10-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='orderproduct',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='recycle',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
