# Generated by Django 5.1.2 on 2024-10-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
