# Generated by Django 5.1.2 on 2024-10-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
